---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/State.yaml
title: CredentialConfig
description: Test scenario action settings
type: object
required:
  - credentialName
  - credentialType
  - credentialJson
additionalProperties: false
properties:
  credentialName:
    description: tbd
    type: string
  credentialType:
    description: tbd
    "$ref": InstanceCredTypes.yaml
  instanceType:
    description: tbd
    type: string
  credentialJson:
    description: tbd
    existingJavaType: com.fasterxml.jackson.databind.JsonNode