---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/State.yaml
title: ScenarioConfigAction
description: The scenario action is an atomic operation. It can be operated inside Airbyte like `Connection creation` or manipulation with source data.
type: object
required:
  - action
additionalProperties: false
properties:
  action:
    description: Action implementation.
    type: object
    existingJavaType: io.airbyte.testingtool.scenario.action.Actions
  resultInstance:
    description: The instance name will be initialized during action execution. The instance should be defined in the ScenarioConfig.usedInstances
    type: string
  requiredInstances:
    description: The list of instance name required for the action execution. The instances should be defined in the ScenarioConfig.usedInstances
    type: array
    items:
      type: string
  requiredParameters:
    description: The list of parameter names required for the action execution.
    type: array
    items:
      "$ref": ScenarioConfigActionParameter.yaml