---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/State.yaml
title: ScenarioConfigInstance
description: Test scenario action settings
type: object
required:
  - instanceName
  - instanceType
additionalProperties: false
properties:
  instanceName:
    description: tbd
    type: string
  instanceType:
    description: tbd
    existingJavaType: io.airbyte.testingtool.scenario.instance.InstanceTypes