---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/State.yaml
title: ScenarioConfig
description: Test scenario action settings
type: object
required:
  - scenarioName
  - preparationActions
  - scenarioActions
additionalProperties: false
properties:
  scenarioName:
    description: tbd
    type: string
  preparationActions:
    description: tbd
    type: array
    items:
      "$ref": ScenarioConfigAction.yaml
  scenarioActions:
    description: tbd
    type: array
    items:
      "$ref": ScenarioConfigAction.yaml