---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/State.yaml
title: CredentialConfig
description: The credential config for instances like Source, Destination, Airbyte, etc.
type: object
required:
  - project_id
  - type
  - private_key_id
  - private_key
  - client_email
  - client_id
  - auth_uri
  - token_uri
  - auth_provider_x509_cert_url
  - client_x509_cert_url
additionalProperties: false
properties:
  project_id:
    description: Project identifier (usually identical to the project name) in Google Cloud.
    type: string
  type:
    description: Connection type. Recommend using service_account type.
    type: string
  private_key_id:
    description: Service account private key identifier.
    type: string
  private_key:
    description: Service account private key.
    type: string
  client_email:
    description: Service account client email.
    type: string
  client_id:
    description: Service account client identifier.
    type: string
  auth_uri:
    description: Authorize URI.
    type: string
  token_uri:
    description: Token URI.
    type: string
  auth_provider_x509_cert_url:
    description: Authorize provider certificate URL.
    type: string
  client_x509_cert_url:
    description: Client certificate URL.
    type: string