---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/State.yaml
title: AirbyteStreamSettings
description: Airbyte Stream Configuration Settings for customize stream.
type: object
required:
  - selected
additionalProperties: false
properties:
  aliasName:
    description: Alias Name
    type: string
  selected:
    description: Selected flag
    type: boolean
  primaryKey:
    description: Primary Key
    type: array
    items:
      type: array
      items:
        type: string
  destinationSyncMode:
    description: Destination Sync Mode
    existingJavaType: io.airbyte.api.client.model.generated.DestinationSyncMode
  cursorField:
    description: Cursor Field
    type: array
    items:
      type: string
  syncMode:
    description: Sync Mode
    existingJavaType: io.airbyte.api.client.model.generated.SyncMode