---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/State.yaml
title: ScenarioConfig
description: The test scenario contains a list of actions required for preparation and execution. Scenario has no credentials and can be reused 
  with different credentials.
type: object
required:
  - scenarioName
  - usedInstances
  - preparationActions
  - scenarioActions
additionalProperties: false
properties:
  scenarioName:
    description: Scenario name. Recommend to keep it unique to understand which scenario is executed from logs.
    type: string
  scenarioDescription:
    description: Brief scenario description. The description is visible on help/list commands.
    type: string
  usedInstances:
    description: List of instance that can be used inside the scenario.
    type: array
    items:
      "$ref": ScenarioConfigInstance.yaml
  preparationActions:
    description: List of actions required to prepare all conditions before the test run.
    type: array
    items:
      "$ref": ScenarioConfigAction.yaml
  scenarioActions:
    description: Test actions.
    type: array
    items:
      "$ref": ScenarioConfigAction.yaml