---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/State.yaml
title: CredentialConfig
description: The credential config for instances like Source, Destination, Airbyte, etc.
type: object
required:
  - credentialName
  - credentialType
additionalProperties: false
properties:
  credentialName:
    description: Credential name. Recommend to keep it unique to avoid duplication in logs.
    type: string
  credentialType:
    description: Credential type.
    "$ref": InstanceCredTypes.yaml
  instanceType:
    description: Instance type name in the Airbyte. For example, the Postgres source is named in the Airbyte `Postgres`.
    type: string
  localInstanceType:
    description: Run local instance instead of using credentialJson for connect.
    existingJavaType: io.airbyte.testingtool.scenario.instance.autonomous.AutonomousInstances
  credentialJson:
    description: Json contains all required credentials for instance creation. Run local instance if it's empty. (If possible)
    existingJavaType: com.fasterxml.jackson.databind.JsonNode
  additionalSettings:
    description: Json contains additional settings. Check `settings` folder for yaml files.
    existingJavaType: com.fasterxml.jackson.databind.JsonNode