---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/State.yaml
title: ConnectionSettings
description: The file contains settings for a custom connection initialization.
type: object
additionalProperties: false
properties:
  connectionName:
    description: TBD
    type: string
  syncCatalogConfig:
    description: Sync Catalog Configuration
    "$ref": catalog/AirbyteCatalogSettings.yaml