name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  slashCommandDispatch:
    # Only allow slash commands on pull request (not on issues)
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR repo and ref
        id: getref
        run: |
          pr_info="$(curl ${{ github.event.issue.pull_request.url }})"
          echo ::set-output name=ref::"$(echo $pr_info | jq -r '.head.ref')"
          echo ::set-output name=repo::"$(echo $pr_info | jq -r '.head.repo.full_name')"
      - name: Slash Command Dispatch
        id: scd
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.AKOROTKOV_PAT }}
          commands: |
            help-full
          static-args: |
            repo=${{ steps.getref.outputs.repo }}
            gitref=${{ steps.getref.outputs.ref }}
            comment-id=${{ github.event.comment.id }}
            comment-body=${{ github.event.comment.body }}
          dispatch-type: workflow
      - name: Edit comment with error message
        if: steps.scd.outputs.error-message && !includes(${{ steps.scd.outputs.error-message }}, "Unexpected inputs provided:")
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > Error: ${{ steps.scd.outputs.error-message }}
