name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  setParams:
    # Only allow slash commands on pull request (not on issues)
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.getref.outputs.repo }}
      ref: ${{ steps.getref.outputs.ref }}
      comment-id: ${{ steps.comment-id.outputs.comment-id }}
      comment-body: ${{ steps.comment-info.outputs.comment-body }}
    steps:
      - name: Get PR repo and ref
        id: getref
        run: |
          pr_info="$(curl ${{ github.event.issue.pull_request.url }})"
          echo ::set-output name=ref::"$(echo $pr_info | jq -r '.head.ref')"
          echo ::set-output name=repo::"$(echo $pr_info | jq -r '.head.repo.full_name')"
      - name: Get comment id
        id: comment-id
        run: echo ::set-output name=comment-id::"${{ github.event.comment.id }}"
      - name: Get comment body
        id: comment-info
        run: |
          full_comment="${{ github.event.comment.body }}"
          comment_without_equal=${full_comment//\=/\|\|}
          echo ::set-output name=comment-body::${comment_without_equal// /\|\|\|}
      - name: Get command
        id: regex
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: "^/[a-zA-Z0-9_/-]+"
          regex_flags: "i"
          search_string: ${{ github.event.comment.body }}
      - name: Update comment for processing
        if: ${{ steps.regex.outputs.first_match }} == "/help-full"
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          edit-mode: replace
          body: ${{ steps.regex.outputs.first_match }}
          reactions: eyes
  slashCommandDispatch:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    needs: setParams
    steps:
      - name: Get command ${{ needs.setParams.outputs.comment-body }}
        run: echo ${{ needs.setParams.outputs.comment-body }}
      - name: Slash Command Dispatch
        id: scd
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.AKOROTKOV_PAT }}
          commands: |
            help-full
          static-args: |
            repo=${{ needs.setParams.outputs.repo }}
            gitref=${{ needs.setParams.outputs.ref }}
            comment-id=${{ needs.setParams.outputs.comment-id }}
            comment-body=${{ needs.setParams.outputs.comment-body }}
          dispatch-type: workflow
      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > Error: ${{ steps.scd.outputs.error-message }}
